# Generated by Django 5.0.7 on 2024-07-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('version', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='player',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('IG', 'In_Game')], default='OF', max_length=2),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.game')),
            ],
        ),
    ]
