# Generated by Django 5.0.7 on 2024-07-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_game_player_avatar_player_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='user_id',
            new_name='user',
        ),
    ]
