# Generated by Django 5.0.7 on 2024-07-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_first_name_customuser_last_name'),
        ('accounts', '0005_rename_game_id_match_game_rename_user_id_player_user'),
    ]

    operations = [
    ]
