# Generated by Django 5.0.7 on 2024-07-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='OF', max_length=2),
        ),
    ]
