# Generated by Django 5.0.7 on 2024-08-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_player_avatar_alter_player_friendship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='friendship',
        ),
    ]
