# Generated by Django 5.0.7 on 2024-08-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_player_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='status',
        ),
    ]
