# Generated by Django 5.0.7 on 2024-08-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='friendship',
            field=models.ManyToManyField(blank=True, related_name='friends', to='accounts.player'),
        ),
    ]
