# Generated by Django 5.0.7 on 2024-08-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_player_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='players', to='accounts.player'),
        ),
    ]
