# Generated by Django 5.0.7 on 2024-08-29 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_match_score_alter_match_date_alter_match_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=125)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_channel', to='accounts.player')),
            ],
        ),
    ]
