# Generated by Django 5.0.7 on 2024-09-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_customuser_otp_customuser_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='ON', max_length=2),
        ),
    ]
