# Generated by Django 5.0.7 on 2024-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_matchgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='privategroup',
            name='blocked_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
