# Generated by Django 5.0.7 on 2024-09-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_privategroup_blocked_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='ON', max_length=2),
        ),
    ]
