# Generated by Django 5.0.7 on 2024-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('SP', 'Single Player'), ('RM', 'Remote'), ('MP', 'Player vs Player')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline')], default='OF', max_length=2),
        ),
    ]
