# Generated by Django 5.0.7 on 2024-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_match_match_type_alter_player_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('AI', 'AI'), ('RM', 'Remote'), ('MP', 'Player vs Player'), ('TN', 'Tournament')], max_length=2, null=True),
        ),
    ]
