# Generated by Django 5.0.7 on 2024-10-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_player_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('AI', 'AI'), ('RM', 'Remote'), ('MP', 'Player vs Player'), ('TN', 'Tournament'), ('3D', '3D-Player vs Player')], max_length=2, null=True),
        ),
    ]
