# Generated by Django 5.0.7 on 2024-11-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
