# Generated by Django 5.0.7 on 2024-11-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_customuser_is_ft_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ON', 'Online'), ('OF', 'Offline'), ('IG', 'In_Game')], default='OF', max_length=2),
        ),
    ]
