#server.name: kibana
server.host: "0.0.0.0"
server.port: 5601
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/kibana.crt
server.ssl.key: /usr/share/kibana/config/certs/kibana.key
elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/certs/ca.crt"]
#elasticsearch.username: "myuser"
#elasticsearch.password: "LLLvFuc4q1V6bzi9mU1P"
#elasticsearch.hosts: [ "https://elasticsearch:9200" ]
elasticsearch.ssl.verificationMode: "none"
elasticsearch.requestTimeout: 60000
monitoring.ui.container.elasticsearch.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "afb7fe8a0b615a7fe3e114149ce62871"
xpack.security.encryptionKey: "afb7fe8a0b615a7fe3e114149ce62871"